language: node_js
sudo: false
node_js:
- 14
install:
- npm install
- npm install --no-save coveralls
script:
- npm run coverage
after_success:
- npm run coveralls
cache:
  directories:
    - node_modules
